# Generated by Django 5.2.16 on 2026-07-10 16:04

from django.db import migrations, models

ORDER_NUMBER_START = 1000


def backfill_order_numbers(apps, schema_editor):
    """Assign existing orders sequential numbers from 1000 in created_at order."""
    Order = apps.get_model("orders", "Order")
    number = ORDER_NUMBER_START
    for order in Order.objects.order_by("created_at", "pk").iterator():
        order.order_number = number
        order.save(update_fields=["order_number"])
        number += 1


def noop_reverse(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.update(order_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='order number'),
        ),
        migrations.RunPython(backfill_order_numbers, noop_reverse),
    ]
