# Generated by Django 5.2.16 on 2026-07-09 22:04

import apps.catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120, verbose_name='name (EN)')),
                ('name_ar', models.CharField(max_length=120, verbose_name='name (AR)')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=60, verbose_name='name (EN)')),
                ('name_ar', models.CharField(max_length=60, verbose_name='name (AR)')),
                ('hex_code', models.CharField(default='#000000', max_length=7, verbose_name='hex code')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, verbose_name='value')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (EN)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (AR)')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (AR)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base price (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', validators=[apps.catalog.validators.validate_image_size], verbose_name='image')),
                ('is_main', models.BooleanField(default=False, verbose_name='main image')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
                'ordering': ['size__sort_order', 'color__name_en'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_ed6a39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
